test: &default

  # Credentials for REST APIs
  client_id: AWrxJiA7P_gVwMpNAfNEWBD6WQwKKGPAgHw7ggBso2jXYYgRXI-EUOeppEXrmwIq2WQbL01yKZZT7wyc
  client_secret: EO5WPlN1J--a1kKoVk-pMfmM14lr6tIQOQjgjb3ZbEP6BdLJshzAqpD3C3K9cZxHOwiKFwjb1jKwVpLO

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
  #Credenciales :)
